# Generated by Django 3.2.8 on 2021-10-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence_request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presencerequest',
            name='approved_at',
        ),
        migrations.AddField(
            model_name='presencerequest',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
    ]
